### ISSUE TITLE
Not retrieving phenylalanine -- [converts to] --> tyrosine edges from semmeddb

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#396] opened 2022-01-25 17:19 UTC
Our semmeddb api currently has 23 associations with subject of phenylalanine (`C0031453`), object of tyrosine (`C0041485`), and predicate of `CONVERTS_TO`. https://biothings.ncats.io/semmeddb/query?q=subject.umls:C0031453%20AND%20object.umls:C0041485%20AND%20predicate:CONVERTS_TO snippet:

```
{
  "took": 2,
  "total": 23,
  "max_score": 25.254173,
  "hits": [
    {
      "_id": "90402291",
      "_score": 25.254173,
      "object": {
        "name": "Tyrosine",
        "novelty": 1,
        "semantic_type_abbreviation": "gngm",
        "semantic_type_name": "Gene or Genome",
        "umls": "C0041485"
      },
      "pmid": 2065777,
      "predicate": "CONVERTS_TO",
      "predication_id": "90402291",
      "subject": {
        "name": "Phenylalanine",
        "novelty": 1,
        "semantic_type_abbreviation": "aapp",
        "semantic_type_name": "Amino Acid, Peptide, or Protein",
        "umls": "C0031453"
      }
    },
    ...
  ]
}
```

In biolink model, `SEMMEDDB:CONVERTS_TO` exactly [maps](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L5179) to `biolink:derives_into`, so I was expecting this TRAPI query to retrieve the results above, but currently reports zero results:

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": ["biolink:derives_into"]
                }
            },
            "nodes": {
                "n00": {
                    "categories": ["biolink:ChemicalEntity"],
                    "ids": ["UMLS:C0041485"]
                },
                "n01": {
                    "categories": ["biolink:ChemicalEntity"],
                    "ids": ["UMLS:C0031453"]
                }
            }
        }
    }
}
```

Perhaps this has to do with a mismatch in semantic types?

related to https://github.com/NCATSTranslator/testing/issues/169

**Comment by tokebe** [comment] 2022-01-25 21:20
BTE appears to be encountering an error with this query: https://api.bte.ncats.io/v1/check_query_status/nGGj3c3lNm. 

I'm investigating further but it would appear that 203 hits are collected from subqueries, and then sent to the edge manager via `updateEdgeResults()` and `updateAllOtherEdges`, but aren't being kept due to the result outputs not matching. This would appear to be because the `UpdatedExeEdge`'s object has no curies. This is reflected in the `qEdge`, which also doesn't have any curies in the object -- implying that the `qEdge` was improperly initialized somehow? I'll be looking into that next...

**Comment by tokebe** [comment] 2022-01-25 21:52
The qEdge is being formed correctly, and the object has the appropriate curie after the queryEdges have been processed. During the execution of `manager.getNext()`, the execution edge's [`chooseLowerEntityValue()`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/987f1aff6cfb38c5729d1372403c337662fda7fa/src/query_execution_edge.js#L36-L63) method is called, which causes the object to "hold" its curie, which appears to not then be returned to its original state when being processed by the edge manager. 

This causes results to not be kept without the code catching a lack of results and terminating the query gracefully, causing the subsequent error. It would seem that for edge updating the object should stop "holding" its curie when the manager begins updating results, however that's starting to approach the boundary for how I understand this algorithm should operate -- @marcodarko might be able to comment further?

**Comment by marcodarko** [comment] 2022-01-25 22:08
@tokebe I'm behind on this conversation but as far as the held curies:
Held curies are put back when curie intersection takes place, so they do get popped back in. but an edge might lose them if the connecting edge doesn't connect to them. line 89ish query_node

**Comment by colleenXu** [comment] 2022-01-26 02:01
It looks a semantic mismatch issue:
* Both of these are amino acids, which one would think of as a chemical / small molecule that's important for bio...
* in SEMMED...the subject Phenylalanine is aapp, which we map to biolink-model's Polypeptide (using biolink-model)
* in SEMMED...the object Tyrosine is gngm, which we map to biolink-model's Gene 
* The SRI ID resolver maps both of these IDs to biolink-model's Protein ([phenylalanine](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=UMLS%3AC0031453&conflate=true), [tyrosine](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=UMLS%3AC0041485&conflate=true)). 
* Polypeptide / Gene / Protein aren't children of ChemicalEntity (instead, they are all children of BiologicalEntity). This visualization [helps](https://tree-viz-biolink.herokuapp.com/)

---

I think there's also an issue with the opening post's query?
It should be "derives_from" as the predicate (Tyrosine derives-from Phenylalanine)...

A query that retrieves the data correctly is  `____ derives-from Phenylalanine`. 

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:derives_from"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:Polypeptide"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ],
                    "ids": [
                        "UMLS:C0031453"
                    ]
                }
            }
        }
    }
}
```

---

note: for the query in the testing repo, the SRI ID resolver doesn't map that [PUBCHEM](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A6140&conflate=true) identifier to the UMLS ID...

**Comment by andrewsu** [comment] 2022-01-26 16:46
To summarize where I think we're at, it appears there are two distinct issues here.  First, there is the 500 error on prod that @tokebe reported in [this comment](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/396#issuecomment-1021619298). I didn't notice the error message in my original post -- I only reported "zero results".

Second, there is the issue of the semantics of the query itself that @colleenXu is raising in [this comment](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/396#issuecomment-1021786871). 

On doing a few quick tests:

| Subject | Predicate | Object | Outcome |
| --------------- | --------------- | --------------- |--------------- |
|  `[Polypeptide]`  | `derives_from` | `[ChemicalEntity] / UMLS:C0031453` | (@colleenXu's query) works as expected
|  `[Polypeptide] / UMLS:C0041485`  | `derives_from` | `[ChemicalEntity] / UMLS:C0031453` | 500 error
|  `[Polypeptide] / UMLS:C0041485`  | `related_to` | `[ChemicalEntity] / UMLS:C0031453` | works as expected

not quite sure what to make of it, but perhaps it's helpful...

**Comment by colleenXu** [comment] 2022-01-26 20:19
Noting other queries that work or don't work:

* The QNode categories are key here. The data is stored with Tyrosine (UMLS:C0041485) as `Gene` and Phenylalanine (UMLS:C0031453) as `Polypeptide`. The sub-query's object has to match the semantic type - since the semantic type is used in the query. The sub-query's input IDs / subject doesn't have to match (since the actual sub-query only uses the subject's ID and not its semantic type). 

* When the QGraph assigns Tyrosine as a `Polypeptide`....I believe this is what happens:
    * BTE uses SRI ID resolver, which assigns the ID as a Protein. 
    * BTE finds metaKG edges from BioThings SEMMEDDB API that go from Polypeptide input ID -(derives_from)-> ____ . The ____ has to be Polypeptide or a parent of Polypeptide for the desired operation.



| Subject | Predicate | Object | Outcome |
| --------------- | --------------- | --------------- |--------------- |
|  `[Polypeptide] / UMLS:C0041485 Tyrosine`  | `derives_from` | `[ChemicalEntity]` | doesn't find Phenylalanine (UMLS:C0031453) since it was mapped to Polypeptide
|  `[Polypeptide] / UMLS:C0041485 Tyrosine`  | `derives_from` | `[Polypeptide]` | works as-expected, finds Phenylalanine

**Comment by tokebe** [comment] 2022-01-26 21:44
Here's a play-by-play of what I'm seeing happening with the non-working query:

<details>
<summary> Using this query </summary>

```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicates": [
            "biolink:derives_from"
          ]
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:Polypeptide"
          ],
          "ids": [
            "UMLS:C0041485"
          ]
        },
        "n01": {
          "categories": [
            "biolink:ChemicalEntity"
          ],
          "ids": [
            "UMLS:C0031453"
          ]
        }
      }
    }
  }
}
```

</details>

Note: both nodes expand to only themselves, with no equivalent identifiers (should this be the case?), just the name and the already given curie.

The edge executes and attempts to store 4 results, each from queries to SEMMEDDB. We've got the following:

- "erythrose 4-phosphate" "CONVERTS_TO" "Tyrosine" (2 input objs, 1 output obj)
- "shikimate" "CONVERTS_TO" "Tyrosine" (2 input objs, 2 output objs)
- "shikimate" "CONVERTS_TO" "Tyrosine" (2 input objs, 2 output objs)
- "Glucose" CONVERTS_TO" "Tyrosine" (2 input objs, 2 output objs)

<details>
<summary> When updating the qEdge's object, this turns into this combined_curies object, which the execution edge attempts to `updateCuries()` the object node with. </summary>

```
{
  "UMLS:C0059572": [
    "PUBCHEM.COMPOUND:122357",
    "CHEMBL.COMPOUND:CHEMBL1232448",
    "UNII:2156QF7O8M",
    "CHEBI:48153",
    "DRUGBANK:DB03937",
    "MESH:C026959",
    "CAS:585-18-2",
    "HMDB:HMDB0001321",
    "KEGG.COMPOUND:C00279",
    "INCHIKEY:NGHMDNPXVRFFGS-IUYQGCFVSA-N",
    "UMLS:C0059572",
    "UMLS:C0891383",
    "UMLS:C0891384",
    "UMLS:C0891385",
    "name:D-Erythrose 4-phosphate",
    "name:CHEMBL1232448",
    "name:ERYTHROSE 4-PHOSPHATE, D-",
    "name:D-erythrose 4-phosphate",
    "name:erythrose 4-phosphate",
    "name:erythrose 4-phosphate, (R*,R*)-isomer",
    "name:erythrose 4-phosphate, 14C4-labeled, (R*,R*)-isomer",
    "name:erythrose 4-phosphate, ((R*,R*)-(+-))-isomer",
  ],
  "UMLS:C0178845": [
    "UMLS:C0178845",
    "name:shikimate",
  ],
  "UMLS:C0017725": [
    "UMLS:C0017725",
    "name:Glucose",
  ],
}
```

</details>

The object node attempts to intersect these with its expanded curies, which consists of only the original phenylalanine. There is no intersection, so no curies are kept. Meanwhile, the qEdge subject updates just fine, having only extracted tyrosine from the results and intersecting successfully as expected.

Subsequently, the edge manager filters results, finding that the output IDs from the results don't intersect with the now 0 curies in the object node (though, there wouldn't have been an intersection anyway, as the phenylalanine ID isn't present in the result output IDs). All 4 results are dropped.

The manager now has 0 results, and the error happens when attempting to `.update()` the query results, as `manager.getOrganizedResults()` returns an empty object, which `query_results._getPreresults()` fails to unpack, expecting there to be an unpackable data structure.

**Comment by tokebe** [comment] 2022-01-26 21:52
@andrewsu @colleenXu @marcodarko This error would appear to be caused by the confluence of a couple separate problems. 

Somewhere between updating the qEdge and the manager returning organized results, or the query results object attempting to update, we should have a check that there are results to work with, and terminate early -- possibly as early as failing to intersect any curies within the qNode.

Additionally, it would appear something might be wrong with either SEMMEDDB, the call-apis package, or the node expander? If we know that SEMMEDDB *should* return a `phenylalanine -> CONVERTS_TO -> tyrosine`, and aren't seeing it in the results, there's probably something else going wrong earlier, likely in the `query_handler`, that's preventing a result from being returned to the `query_graph_handler` with the expected edge.

This will probably be my next area of focus for tracking this down, comparing to the queries that do work. We may wish to open a separate issue specific to the actual error happening here, as we probably want to cover cases where 0 results somehow get this far with some query-terminating check.

**Comment by marcodarko** [comment] 2022-01-26 23:47
@tokebe after each edge is executed we check if there was no results here: https://github.com/biothings/bte_trapi_query_graph_handler/blob/987f1aff6cfb38c5729d1372403c337662fda7fa/src/index.js#L213
So if it made it past this part then when the manager collects the results is just simply going edge by edge combining and organizing the results by edge.  So it would be weird for me that the collection would find 0 results.  I suspect it's something else perhaps.

**Comment by andrewsu** [comment] 2022-01-27 05:55
> Additionally, it would appear something might be wrong with either SEMMEDDB, the call-apis package, or the node expander? If we know that SEMMEDDB should return a phenylalanine -> CONVERTS_TO -> tyrosine, and aren't seeing it in the results, there's probably something else going wrong earlier, likely in the query_handler, that's preventing a result from being returned to the query_graph_handler with the expected edge.

So it _could_ be the issue of the mismatch of semantic types that @colleenXu posted [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/396#issuecomment-1021786871).  To properly diagnose that, it would be useful to see the actual semmeddb API calls that BTE is accessing.  From that, we should be able to quickly determine whether the tyrosine-phenylalanine edge is actually sent back from any of those API calls (indicating a BTE parsing issue of the API results) or whether the edge is not absent (suggesting BTE is not properly creating the API calls -- likely due to the semantic type mismatches)...

**Comment by colleenXu** [comment] 2022-01-27 06:33
@tokebe to follow-up on what @andrewsu said:

I think the query used [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/396#issuecomment-1022630667) will end up with **0 results and an empty knowledge-graph section**. This is because the semantic issues - the sub-query will not retrieve the Phenylalanine-Tyrosine data:
* It looks like BTE decides to use n00 as the "input node".
* It's then going to use the semantic type for the n01 QNode as the output semantic type for the operation. Which is ChemicalEntity. **This is the problem** because those operations won't actually retrieve the data for the Tyrosine ID. Because in the API/data, the Tyrosine ID is set as a Gene (gngm). 

I also describe this and give more examples below

---

I'm worried that the semantic mismatch issue is obscuring what is happening with the 500 error. To me, the 500 error sounds like an issue where BTE isn't correctly handling the "0 records after doing an intersection"...

**Comment by colleenXu** [comment] 2022-01-27 06:37
Also, the queries I've done so far and what I think of their behavior (since I think I understand the semantic issues here...):

This is based on querying from Tyrosine. I imagine that something similar will play out if we queried starting from Phenylalanine.

| Subject | Predicate | Object | Outcome |
| --------------- | --------------- | --------------- |--------------- |
|  `[no semantic type] / UMLS:C0041485 / Tyrosine `  | `derives_from` | `[ChemicalEntity]` | doesn't work, which is expected. BTE looks for operations to `ChemicalEntity`....while Phenylalanine is actually under `Polypeptide`. &#119070;
|  `[Polypeptide] / UMLS:C0041485 / Tyrosine `  | `derives_from` | `[ChemicalEntity]` | doesn't work, which is expected. Same reason as above. The subject's semantic type only matters in some cases, like below. 
|  `[no semantic type] / UMLS:C0041485 / Tyrosine `  | `derives_from` | `[Polypeptide]` | doesn't work (no operations found)...the object is now specified correctly....but the reason for no operations is probably that `Protein-(derives_from)->Polypeptide` or its inverse didn't exist in the original data (with > 100 matching records). 
|  `[ChemicalEntity] / UMLS:C0041485 / Tyrosine `  | `derives_from` | `[Polypeptide]` | this works, even though semantic types for Tyrosine (`ChemicalEntity`,`Protein` from SRI) don't match the data's (`Gene`). This is because there is an operation/meta-triple (`ChemicalEntity -(derives_from)-> Polypeptide`) and the operation's sub-query only uses the ID from the subject (its semantic type mismatch then doesn't matter). The Phenylalanine data is under aapp/`Polypeptide` so it then is successfully retrieved
|  `[Gene] / UMLS:C0041485 / Tyrosine `  | `derives_from` | `[Polypeptide]` | this works, as expected. The semantic types for the QNodes here matches the semantic types of the operation/sub-query we want to do. 


---

note on how the operations for semmeddb api work (which explains why we can handle some semantic mismatches and not handle others):
* The operations are made based on the semantic terms IN THE DATA, which are SEMMEDDB semantic vocab. Those are mapped to what Translator uses (biolink-model). 
* the sub-queries use the subject's ID, the semmeddb predicate, and the object's semmeddb semantic type. That is why the object semantic type matters so much for the operations/sub-queries. 
* the subject semantic type will only matter when the operation/meta-triple doesn't actually exist in the data (see the third row above)


&#119070; Weird..I thought there was code to include "Gene" whenever "Protein" came up in a QGraph. I guess it doesn't work when Protein comes up in the SRI ID resolution?

**Comment by colleenXu** [comment] 2022-01-27 07:12
Yup, If we switch to querying starting from Phenyalanine, the same thing happens. Only including here as FYI 

<details>
<summary>expand here</summary>

| Subject | Predicate | Object | Outcome |
| --------------- | --------------- | --------------- |--------------- |
|  `[no semantic type] / UMLS:C0031453 / Phenylalanine `  | `derives_into` | `[ChemicalEntity]` | doesn't work, which is expected. BTE looks for operations to `ChemicalEntity`....while Tyrosine is actually under `Gene`.
|  `[Polypeptide] / UMLS:C0031453 / Phenylalanine `  | `derives_into` | `[ChemicalEntity]` | doesn't retrieve Tyrosine, which is expected. Same reason as above. The subject's semantic type only matters in some cases, like below. 
|  `[no semantic type] / UMLS:C0031453 / Phenylalanine `  | `derives_into` | `[Gene]` | doesn't work (no operations found)...the object is now specified correctly....but the reason for no operations is probably that `Protein-(derives_into)->Gene` or its inverse didn't exist in the original data (with > 100 matching records). 
|  `[ChemicalEntity] / UMLS:C0031453 / Phenylalanine `  | `derives_into` | `[Gene]` | this works, even though semantic types for Phenylalanine (`ChemicalEntity`,`Protein` from SRI) don't match the data's (`Polypeptide`). This is because there is an operation/meta-triple (`ChemicalEntity -(derives_into)-> Gene`) and the operation's sub-query only uses the ID from the subject (its semantic type mismatch then doesn't matter). The Tyrosine data is under gngm/`Gene` so it then is successfully retrieved
|  `[Polypeptide] / UMLS:C0031453 / Phenylalanine `  | `derives_into` | `[Gene]` | this works, as expected. The semantic types for the QNodes here matches the semantic types of the operation/sub-query we want to do. 

</details>

**Comment by tokebe** [comment] 2022-01-27 17:26
> @tokebe after each edge is executed we check if there was no results here: https://github.com/biothings/bte_trapi_query_graph_handler/blob/987f1aff6cfb38c5729d1372403c337662fda7fa/src/index.js#L213 So if it made it past this part then when the manager collects the results is just simply going edge by edge combining and organizing the results by edge. So it would be weird for me that the collection would find 0 results. I suspect it's something else perhaps.

@marcodarko See [my above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/396#issuecomment-1022630667) comment -- we get results from the query handler, but after the edge attempts to store them, no results are kept. As there are no subsequent checks, the lack of results make it through. I'm writing a PR to check at a slightly later stage as well.

I'm also just going to echo that this error is basically a separate issue (see [slack post](https://suwulab.slack.com/archives/CC218TEKC/p1643268088134800) from @colleenXu) - after it is fixed, we will still have the issue of the target edge not being retrieved to deal with.

**Comment by tokebe** [comment] 2022-01-27 19:59
@andrewsu biothings/bte_trapi_query_graph_handler/pull/87 Should fix the error. @colleenXu [expressed in the Slack](https://suwulab.slack.com/archives/CC218TEKC/p1643311780143300?thread_ts=1643268088.134800&cid=CC218TEKC) that the lack of retrieval isn't a problem...so I guess this issue will be resolved once the PR is deployed?

**Comment by colleenXu** [comment] 2022-01-28 01:52
just a note: all the queries above have been POST to http://localhost:3000/v1/smartapi/1d288b3a3caf75d541ffaae3aab386c8/query (semmeddb thru BTE specifically)

**Comment by tokebe** [comment] 2022-03-02 18:42
Marking as closed as fix is deployed and issue is marked as awaiting closing.

**Closed as completed by tokebe** 2022-03-02 18:42 UTC
Labels: bug

**Comment by colleenXu** [comment] 2022-03-03 01:56
I agree to close this issue. I had opened #400 as a clearer explanation of the "500 bug when two QNodes with IDs aren't found to be connected to each other"...

This issue also describes a semantic issue in SEMMEDDB, which led to https://github.com/TranslatorSRI/Babel/issues/530.
