### ISSUE TITLE
create normalized google distance handler for semmed API

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#326] opened 2021-10-20 19:39 UTC
We would like to use semmeddb to compute the normalized google distance (NGD) for two concepts, but this is currently not feasible based on the API at https://pending.biothings.io/semmeddb.  After talking with @newgene, he suggest that this could be implemented as a custom ES handler and a new, dedicated API endpoint.

**Comment by erikyao** [comment] 2021-11-01 21:29
# (Deprecated. See the latest comments for API specification)

<details><summary>Click to expand</summary>

## Overview

The API is published to the endpoint https://biothings.ncats.io/semmeddb/query/ngd. The related code commit is [ced3717](https://github.com/biothings/pending.api/commit/ced3717275bf30d407a7d122283eda5b0c6bfe40) (N.B. not merged to `master` yet.)

E.g. to query the Normalized Google Distance between ID `C0684074` ("rams") and `C0003063` ("Animals, Domestic"), we can use:

- https://biothings.ncats.io/semmeddb/query/ngd?q=subject.umls:C0684074%20AND%20object.umls:C0003063

The response would be an json object representing the two IDs and their distance, as in:

```json
{
  "subject.umls": "C0684074",
  "object.umls": "C0003063",
  "ngd": 0.8219458152012636
}
```

## Query String Format

The `q` string format is: `<scope>:<id> AND <scope>:<id>`, where:

- the logical operator must be `AND`, and the flanking spaces are required;
- `<scope>` can be either `subject.umls` or `object.umls`, and the order does not matter;
- `<id>` must be valid SemmedDB umls. 

Error handling can be further improved but now most errors are represented as `500: Internal Server Error`.

## Bi-directional Relationship

The calculation of Normalized Google Distance involves counting the number of documents for a single ID or a pair of IDs. Although we specify `subject.umls` or `object.umls` in the query string, internally we will count all the documents containing the `<id>`, regardless of subject or object it is as. (This practice is following the idea proposed in https://github.com/biothings/pending.api/issues/20)

E.g. the number of documents containing `C0684074` ("rams") is counted like:

```SQL
COUNT(1) from SemmedDB where subject.umls="C0684074"
    PLUS
COUNT(1) from SemmedDB where object.umls="C0684074"
```

Similarly, the number of documents containing two IDs are counted like:

```SQL
COUNT(1) from SemmedDB where subject.umls="C0684074" and object.umls="C0003063"
    PLUS
COUNT(1) from SemmedDB where object.umls="C0684074" and subject.umls="C0003063"
```

## Caching

The number of documents can be cached to reduce duplicated counting operations. Currently there are 4 caches, as shown in the table below:

|Key           |Cached Value                                      | Size  |Comment|
|--------------|--------------------------------------------------|-------|-------|
|ID            | count of documents containing ID                 | 10240 | LRU (Least Recently Used) |
|(ID_1, ID_2)  | count of documents containing both IDs           | 10240 | LRU   |
|N/A           | count of all documents in SemmedDB.              | 1    | Static member of the handler class |
|(ID_1, ID_2)  | Normalized Google Distance between these two IDs | 10240 | LRU   |

We can further increase the sizes of the above 3 LRU caches for better performance if necessary.

</details>

**Comment by erikyao** [comment] 2021-11-04 01:12
# (Deprecated. See the latest comments for API specification)

<details>
<summary>Click to expand</summary>

## Examples of Corner Cases and Error Handling

### Undefined NGD

- Cause: a term never occurs in the corpus
- Query string: `q=subject.umls:C0684074 AND object.umls:C0003063xx`
- URL: https://biothings.ncats.io/semmeddb/query/ngd?q=subject.umls:C0684074%20AND%20object.umls:C0003063xx

```python
{
  "code": 200,
  "success": false,
  "error": "NGD is undefined because the count of term 'C0003063xx' is 0 in SemMedDB API."
}
```

### Infinite NGD

- Cause: when two terms that separately occur in the corpus, but never occur together
- Query string: `q=subject.umls:C0684074 AND object.umls:C0282687`
- URL: https://biothings.ncats.io/semmeddb/query/ngd?q=subject.umls:C0684074%20AND%20object.umls:C0282687

```python
{
  "subject.umls": "C0684074", 
  "object.umls": "C0282687", 
  "ngd": Infinity
}
```

N.B. `Infinity` is a [JS global property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity), not a string. Please let me know if it's difficult to process.

### Empty Query String

- URL: https://biothings.ncats.io/semmeddb/query/ngd

```python
{
  "code": 400,
  "success": false,
  "error": "Must input a query string, e.g. 'q=subject.umls:C0684074 AND object.umls:C0003063'."
}
```

### Incomplete Query String

- Query string: `q=subject.umls:C0684074`
- URL: https://biothings.ncats.io/semmeddb/query/ngd?q=subject.umls:C0684074

```python
{
  "code": 400,
  "success": false,
  "error": "Input query string must have 3 components, 'ENTITY1 AND ENTITY2'. Got 'subject.umls:C0684074' with only 1 component(s)."
}
```

### Wrong Operator

- Query string: `q=subject.umls:C0684074 OR object.umls:C0003063`
- URL: https://biothings.ncats.io/semmeddb/query/ngd?q=subject.umls:C0684074%20OR%20object.umls:C0003063

```python
{
  "code": 400,
  "success": false,
  "error": "Input query string must use AND operator. Got 'subject.umls:C0684074 OR object.umls:C0003063' with OR operator."
}
```

### Wrong Scope

- Query string: `q=a:C0684074 AND b:C0003063`
- URL: https://biothings.ncats.io/semmeddb/query/ngd?q=a:C0684074%20AND%20b:C0003063

```python
{
  "code": 400,
  "success": false,
  "error": "An entity in input query string must have a scope in {'subject.umls', 'object.umls'}. Got 'a:C0684074' with 'a' as a scope."
}
```

</details>

**Comment by andrewsu** [comment] 2021-11-04 04:59
Hmm, the `Infinity` validates with the python json library. But it confuses all sorts of online json validators, and probably most importantly, javascript's json parser:

![image](https://user-images.githubusercontent.com/2635409/140260318-7d8be16a-407f-493a-aac3-2e7045fb55dc.png)

any thoughts on how to deal with that?

**Comment by erikyao** [comment] 2021-11-09 02:32
Hi @andrewsu & @ericz1803 , could you please let me know how you'd like to pass the parameters to batch queries? I came up with 2 options below. New ideas are also welcome. Thanks!

### Option 1. Pass in a list of ID pairs, and then compute NGD for each pair. 

E.g:

```python
{
    "umls": [
        ["C01", "C02"],
        ["C01", "C03"],
        ["C02", "C03"]
    ]
}
```

- Returns:
    - `NGD('C01', 'C02')`
    - `NGD('C01', 'C03')`
    - `NGD('C02', 'C03')`
- I.e. `n` pairs => `n` scores

### Option 2. Pass in a list of IDs, and then compute NGD for each combination (_k=2_) of IDs. 

E.g. 

```python
{
    "umls": ["C01", "C02", "C03"]
}
```

- Returns:
    - `NGD('C01', 'C02')`
    - `NGD('C01', 'C03')`
    - `NGD('C02', 'C03')`
- I.e. `n` IDs => `(n choose 2)` scores

**Comment by andrewsu** [comment] 2021-11-09 04:49
I think Option 1 will be much more appropriate for our use case...

**Comment by erikyao** [comment] 2021-11-09 19:21
@andrewsu sounds good! working on it now...

**Comment by erikyao** [comment] 2021-11-10 23:59
## 1. Overview

The API is published to the endpoint https://biothings.ncats.io/semmeddb/query/ngd. The related code commit is [2ccd0e2](https://github.com/biothings/pending.api/commit/2ccd0e2a7f68b2e8d4beff3df1610d6ca09bdce2)

## 2. Normalized Google Distance (NGD)

### 2.1 How to Calculate

The calculation of NGD follows the formula in [wikipedia](https://en.wikipedia.org/wiki/Normalized_Google_distance). Specially:

- If `f(x) > 0` and `f(y) > 0`, while `f(x, y) == 0`, `NGD(x, y)` is _**infinite**_
- If `f(x) == 0` or `f(y) == 0`, `NGD(x, y)` is _**undefined**_

where `f(x)` and `f(y)` are the numbers of documents containing `x` and `y` respectively; `f(x, y)` is the number of documents containing both `x` and `y`.

**N.B.** we also use _**undefined**_ as an error code in our API. See the specification below.

### 2.2 Counting the Number of Documents for NGD

To get `f(x)`, where `x` is a UMLS identifier in our API, internally we will count all the documents containing `x`, regardless of subject or object it is as. (This practice is following the idea proposed in https://github.com/biothings/pending.api/issues/20)

E.g. the number of documents containing `C0684074` ("rams") is counted like:

```SQL
COUNT(1) from SemmedDB where subject.umls="C0684074"
    PLUS
COUNT(1) from SemmedDB where object.umls="C0684074"
```

Similarly, to get `f(x, y)`, the number of documents containing two UMLS identifiers are counted like:

```SQL
COUNT(1) from SemmedDB where subject.umls="C0684074" and object.umls="C0003063"
    PLUS
COUNT(1) from SemmedDB where object.umls="C0684074" and subject.umls="C0003063"
```

### 2.3 Caching

The number of documents, along with calculated NGD, can be cached to reduce duplicated operations. Currently there are 4 caches, as shown in the table below:

|Key           |Cached Value                                   | Size  |Comment|
|--------------|-----------------------------------------------|-------|-------|
|`x`           | count of docs containing `x`, i.e. `f(x)`     | 10240 | LRU (Least Recently Used) |
|`(x, y)`      | count of docs containing both, i.e. `f(x, y)` | 10240 | LRU   |
|N/A           | count of all docs in SemmedDB                 | 1     | Static member of the handler class |
|`(x, y)`      | NGD of `(x, y)`                               | 10240 | LRU   |

We can further increase the sizes of the above 3 LRU caches for better performance if necessary.

## 3. Single Queries with `GET` Method

E.g. to query the NGD between umls `C0684074` ("rams") and `C0003063` ("Animals, Domestic"), we can use:

- https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063

The response would be an json object representing the two IDs and their distance, as in:

```json
{
  "umls": [
    "C0684074",
    "C0003063"
  ],
  "ngd": 0.8219458152012636
}
```

### 3.1 Query String Format

The string format is: `umls=<ID1><separator><ID2>`, where:

- the `<separator>` can be any single character within `\t\n\x0b\x0c\r |,+` (i.e. _tab, newline, vertical tab, [form feed](https://en.wikipedia.org/wiki/Page_break#Form_feed), carriage return, single space, vertical bar, comma, plus sign_)
   - Technically the `<separator>` is split by in [split_ids() function](https://github.com/biothings/biothings.api/blob/master/biothings/utils/common.py#L254)
- `<ID1>` and `<ID2>` must be valid SemmedDB UMLS identifiers. 

### 3.2 Corner Cases and Error Messages

#### 3.2.1 Undefined NGD

- Cause: a term never occurs in the corpus
- URL: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063x

```python
{
  "umls": [
    "C0684074",
    "C0003063x"
  ],
  "ngd": "undefined",
  "reason": "the count of term 'C0003063x' is 0 in SemMedDB API."
}
```

### 3.2.2 Infinite NGD

- Cause: when two terms that separately occur in the corpus, but never occur together
- URL: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0282687

```python
{
  "umls": [
    "C0684074",
    "C0282687"
  ],
  "ngd": "Infinity"
}
```

**N.B.** I changed the infinity value to a string, instead of the [`Infinity` property in JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity).

### 3.2.3 Empty Query String

- URL: https://biothings.ncats.io/semmeddb/query/ngd

```python
{
  "code": 400,
  "success": false,
  "error": "Bad Request",
  "missing": "umls"
}
```

### 3.2.4 Only 1 ID, or more than 2 IDs

- URL: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074

```python
{
  "code": 400,
  "success": false,
  "error": "Exact 2 umls are required. Got 1."
}
```

- URL: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0282687,C0037868

```python
{
  "code": 400,
  "success": false,
  "error": "Exact 2 umls are required. Got 3."
}
```

### 3.2.5 Wrong Separator

- URL: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074~C0282687

```python
{
  "code": 400,
  "success": false,
  "error": "Exact 2 umls are required. Got 1."
}
```

**N.B.** A wrong separator will fundamentally affect the parsing of the URL, so it's a little bit hard to return the precise error messages. In the above case, our API will only receive one ID, `C0684074`, associated with the parameter `umls`. Therefore, the error message is the same as the one in _Sec. 3.2.4_.

## 4. Batch Queries with `POST` Method

E.g. to query the NGDs between 

1. `C0684074` ("rams") and `C0003063` ("Animals, Domestic"), plus 
2. `C0007450` ("cats") and `C0007350` ("Feline Disease")

We can use:

```bash
curl -X POST http://biothings.ncats.io/semmeddb/query/ngd -H 'Content-Type: application/json'  -d '{"umls": [["C0684074", "C0003063"], ["C0007450", "C0007350"]]}'
```

- Of course you can choose other tools other than `curl` to make a POST request.

The response would be an JSON list, each member being the result for a pair of IDs respectively, as in:

```json
[
  {
    "umls": [
      "C0684074",
      "C0003063"
    ],
    "ngd": 0.8219458152012636
  },
  {
    "umls": [
      "C0007450",
      "C0007350"
    ],
    "ngd": 0.6338402662927998
  }
]
```

### 4.1 Structure of the Request Body

The request body associated with a batch query is a JSON object like:

```python
{
    "umls": [
        ["C0684074", "C0003063"], 
        ["C0007450", "C0007350"],
        ......
    ]
}
```

where:

- the only accepted parameter key is `"umls"`
- the value of the parameter must be a list of 2-ID sublists
    - **at most 1000** sublists can be sent in one batch

### 4.2 Corner Cases and Error Messages

See _Sec. 3.2_ for reference. 

A single error caused by one sublist will NOT fail the whole batch query. E.g.  

```bash
curl -X POST http://biothings.ncats.io/semmeddb/query/ngd -H 'Content-Type: application/json'  -d '{"umls": [["C0684074", "C0003063"], ["C0007450"]]}'
```

```python
[
  {
    "umls": [
      "C0684074",
      "C0003063"
    ],
    "ngd": 0.8219458152012636
  },
  {
    "umls": [
      "C0007450"
    ],
    "ngd": "undefined",
    "reason": "Exact 2 umls are required. Got 1."
  }
]
```

**Closed as completed** 2021-12-07 18:17 UTC
