### ISSUE TITLE
query graph validation error

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#183] opened 2021-05-20 16:29 UTC
reported here: https://github.com/NCATSTranslator/minihackathons/issues/9

**Comment by newgene** [comment] 2021-05-25 03:04
Example query:

```
curl --location --request POST 'https://dev.api.bte.ncats.io/v1/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                },
                "n1": {
                    "name": "EGFR",
                    "ids": [
                        "NCBIGene:1956"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:decreases_abundance_of",
                        "biolink:decreases_activity_of",
                        "biolink:decreases_expression_of",
                        "biolink:decreases_synthesis_of",
                        "biolink:increases_degradation_of",
                        "biolink:disrupts",
                        "biolink:negatively_regulates_entity_to_entity"
                    ]
                }
            }
        }
    }
}'
```

**Comment by andrewsu** [comment] 2021-06-07 16:26
I believe this is a duplicate issue of #171, but let's confirm after that one is resolved.

**Comment by colleenXu** [comment] 2021-06-16 23:44
This was a duplicate of #171, and #171 has been resolved. Look there for info.

**Closed as completed by colleenXu** 2021-06-16 23:44 UTC
Labels: bug
