### ISSUE TITLE
how to query by UniProtKB CURIE?

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#99] opened 2021-03-12 16:23 UTC
The issue at https://github.com/NCATSTranslator/testing/issues/10 reports that BTE does not return any results for the following query:

```
{
	"message": {
		"query_graph": {
			"nodes": {
				"n0": {
					"id": "UniProtKB:P52788",
					"category":"biolink:Gene"
				},
				"n1": {
					"category": "biolink:ChemicalSubstance"
                }
			},
			"edges": {
				"e01": {
					"subject": "n0",
                                        "object": "n1"
                                }
			}
		}
	}
}
```

If I convert `UniProtKB:P52788` to `NCBIGENE:6611` (based on http://mygene.info/v3/query?q=P52788&fields=entrezgene,uniprot), the query returns many results as expected.  I tried adjusting the `category` for `n0` to `biolink:Protein` and `biolink:GenomicEntity`, but those queries also return zero results.  What is the proper way to form a BTE TRAPI query for a UniProtKB CURIE?

**Comment by kevinxin90** [comment] 2021-03-12 16:47
Oh, we use the wrong UniProtKB ID (in our ID resolution module, we used UNIPROTKB instead of UniProtKB)

**Comment by kevinxin90** [comment] 2021-03-12 16:59
The issue is fixed now. @andrewsu Feel free to try agin.

**Closed as completed by kevinxin90** 2021-03-12 16:59 UTC

**Comment by andrewsu** [comment] 2021-03-12 17:09
confirmed, thanks!  For posterity, linking to https://github.com/biothings/BioThings_Explorer_TRAPI/commit/92fac04398329d3dec5d579ed5dcf1d397d515ee and https://github.com/kevinxin90/biomedical_id_resolver.js/commit/79be269e2f4480cdce62a4d21cf7e0283cf552e2
