### ISSUE TITLE
NodeNotFound for `Bacterium` and `Virus`

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#691] opened 2023-08-10 20:29 UTC
Sentry is alerting us to these errors (lab Slack posts; there may be a few more I'm not linking)
* [Bacterium 1](https://suwulab.slack.com/archives/CC218TEKC/p1691509417147569), [Bacterium 2](https://suwulab.slack.com/archives/CC218TEKC/p1691509453496809)
* [Virus](https://suwulab.slack.com/archives/CC218TEKC/p1691611620479709)

From a quick look, these errors are happening when we're used as a KP (Service Provider team endpoint) by Aragorn, and it's sending ChemicalEntity and lots of IDs -> NamedThing. BTE is likely coming across MetaEdges / sub-queries that have Bacterium / Virus in the answer or query-graph. 

It's not clear if this is related to:
* [semmeddb x-bte annotation updates](https://github.com/biothings/biothings_explorer/issues/669#issuecomment-1670715251) (expand the collapsed section of added operations, to see that bacterium / virus operations were added)
* [updating to biolink-model 3.5.3](https://github.com/biothings/biothings_explorer/issues/661#issuecomment-1668734502) (is it possible that there's any issues with this biolink-model version?)

**Comment by colleenXu** [comment] 2023-08-10 20:30
@tokebe I put this into the milestone as a bug to address, but I'll leave it to you to decide whether we need to address it for code freeze or not

**Comment by tokebe** [comment] 2023-08-10 20:49
One such query to reproduce this error:

```json
{
  "message": {
    "query_graph": {
      "edges": {
        "edge_2": {
          "attribute_constraints": [],
          "object": "e",
          "predicates": [
            "biolink:has_part"
          ],
          "qualifier_constraints": [],
          "subject": "i"
        }
      },
      "nodes": {
        "e": {
          "categories": [
            "biolink:ChemicalEntity"
          ],
          "constraints": [],
          "ids": [
            "CHEMBL.COMPOUND:CHEMBL1201587",
            "CHEMBL.COMPOUND:CHEMBL4650433",
            "CHEMBL.COMPOUND:CHEMBL1201572",
            "CHEMBL.COMPOUND:CHEMBL4298176",
            "UMLS:C0072980",
            "MESH:D016756",
            "CHEMBL.COMPOUND:CHEMBL1201607",
            "UMLS:C0031465",
            "UMLS:C0170531",
            "CHEMBL.COMPOUND:CHEMBL2107726",
            "CHEMBL.COMPOUND:CHEMBL3137353",
            "CHEMBL.COMPOUND:CHEMBL3545374",
            "CHEMBL.COMPOUND:CHEMBL1201570"
          ],
          "is_set": false
        },
        "i": {
          "categories": [
            "biolink:NamedThing"
          ],
          "constraints": [],
          "is_set": false
        }
      }
    }
  },
  "submitter": "infores:aragorn"
}
```

**Comment by tokebe** [comment] 2023-08-10 20:57
Strange, both Virus and Bacterium are in the current `biolink.yaml` that BTE uses, and I can even confirm `OrganismalEntity` as being present in the tree that BTE constructs from the model, but somehow those two are missing...

**Comment by rjawesome** [comment] 2023-08-10 22:07
![image](https://github.com/biothings/biothings_explorer/assets/16053597/2c93df71-6288-4cc4-93e9-50fe38747ea2)
The issue seems to be that biomedical_id_resolver is using its own node_modules rather than the packages for biolink model (I assume npm's package is outdated)

(https://github.com/biothings/biomedical_id_resolver.js/blob/main/package.json. Removing biolink-model from this package.json might solve the issue?)

EDIT: Seems to be working locally when I delete the biolink-model folder from biomedical_id_resolver's node modules

**Comment by tokebe** [comment] 2023-08-11 14:12
Great investigative work @rjawesome! I've pushed a fix to address this issue: https://github.com/biothings/biomedical_id_resolver.js/commit/332b272c9af243ed7e2b2d6b9bd78550f85226aa

**Closed as completed** 2023-08-23 16:18 UTC
Labels: bug, On Test
