### ISSUE TITLE
Bug: DGIdb not being queried correctly

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#362] opened 2021-12-03 17:18 UTC
In https://github.com/NCATSTranslator/testing/issues/151, the query (pasted below) asks for compounds related to `NCBIGene:7979` via several predicates, including `biolink:decreases_activity_of`, with bortezimib as a positive control.  the BioThings API for DGIdb contains this link (see https://biothings.ncats.io/dgidb/query?q=subject.NCBIGene:7979, snippet below) but it is not being returned when posting to either https://api.bte.ncats.io/v1/query or https://api.bte.ncats.io/v1/smartapi/e3edd325c76f2992a111b43a907a4870/query.  I assume this has to do with the smartAPI x-bte annotations for DGIdb? 

**Query**:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates": [
                        "biolink:entity_negatively_regulates_entity",
                        "biolink:decreases_abundance_of", 
                        "biolink:decreases_expression_of", 
                        "biolink:decreases_stability_of", 
                        "biolink:decreases_uptake_of", 
                        "biolink:increases_degradation_of", 
                        "biolink:decreases_synthesis_of", 
                        "biolink:decreases_activity_of"
                    ]
                }
            },
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:7979"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            }
        }
    }
}
```

**DGIdb snippet**:
```
{
  "took": 0,
  "total": 6,
  "max_score": 8.455176,
  "hits": [
    {
      "_id": "d86ff0fa9ff42d29",
      "_score": 8.455176,
      "association": {
        "edge_label": "decreases_activity_of",
        "interaction_group_score": "0.47",
        "provided_by": "ChemblInteractions",
        "relation_name": "inhibitor"
      },
      "object": {
        "CHEMBL_COMPOUND": "CHEMBL.COMPOUND:CHEMBL325041",
        "id": "CHEMBL.COMPOUND:CHEMBL325041",
        "name": "BORTEZOMIB"
      },
      "subject": {
        "NCBIGene": "7979",
        "SYMBOL": "SEM1",
        "id": "NCBIGene:7979"
      }
    },
```

**Comment by colleenXu** [comment] 2021-12-09 06:31
@andrewsu looks like the x-bte annotations group all of the associations in this api into 1 relationship with the predicate "physically_interacts_with".

It looks like whoever made the parser for this api mapped the relationships in dgidb to biolink predicates (likely an old version of biolink-model).

It looks like there are a LOT of possible meta-triples in this api...I'm not sure if we want to create separate operations for each one...

Notes:
* x-bte annotation currently has NCBIGene gene <-> Chembl.compound smallmolecule operations
* looks like there are many original dgidb relationships stored under association.relation_name and biolink model predicate mapping under association.edge_label - and both fields **can have more than one relationship**. 


My review of the API (70,248 documents) + components of meta-triples:
* looks like all records have [subject.NCBIGene](https://biothings.ncats.io/dgidb/query?q=_exists_:subject.NCBIGene)
* looks like all records have [object.CHEMBL_COMPOUND](https://biothings.ncats.io/dgidb/query?q=_exists_:object.CHEMBL_COMPOUND)
* old biolink model mapping + dgidb relationships
    * currently mapped to physically_interacts_with (49899 records). Looks like these are records without any relation?
    * currently mapped to decreases_activity_of (14265 records)
        * 9093 records have [inhibitor](https://biothings.ncats.io/dgidb/query?q=association.relation_name:inhibitor)
        * 3936 records have [antagonist](https://biothings.ncats.io/dgidb/query?q=association.relation_name:antagonist)
        * 1167 records have [blocker](https://biothings.ncats.io/dgidb/query?q=association.relation_name:blocker)
        * 49 records have [inverse_agonist](https://biothings.ncats.io/dgidb/query?q=association.relation_name:inverse_agonist)
        * 41 records have [negative_modulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:negative_modulator)
        * 8 records have [vaccine](https://biothings.ncats.io/dgidb/query?q=association.relation_name:vaccine)
        * 6 records have [suppressor](https://biothings.ncats.io/dgidb/query?q=association.relation_name:suppressor)
        * 5 records have [inhibitory_allosteric_modulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:inhibitory_allosteric_modulator)
        * 2 records have [partial_antagonist](https://biothings.ncats.io/dgidb/query?q=association.relation_name:partial_antagonist)
    * currently mapped to increases_activity_of (4353 records)
        * 3304 records have [agonist](https://biothings.ncats.io/dgidb/query?q=association.relation_name:agonist)
        * 667 records have [positive_modulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:positive_modulator)
        * 158 records have [partial_agonist](https://biothings.ncats.io/dgidb/query?q=association.relation_name:partial_agonist)
        * 136 records have [potentiator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:potentiator)
        * 78 records have [inducer](https://biothings.ncats.io/dgidb/query?q=association.relation_name:inducer)
        * 22 records have [stimulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:stimulator)
    * currently mapped to directly_interacts_with (707 records)
        * 286 records have [ligand](https://biothings.ncats.io/dgidb/query?q=association.relation_name:ligand) 
        * 254 records have [binder](https://biothings.ncats.io/dgidb/query?q=association.relation_name:binder) 
        * 142 records have [cofactor](https://biothings.ncats.io/dgidb/query?q=association.relation_name:cofactor) 
        * 10 records have [multitarget](https://biothings.ncats.io/dgidb/query?q=association.relation_name:multitarget) 
        * 10 records have [chaperone](https://biothings.ncats.io/dgidb/query?q=association.relation_name:chaperone) 
        * 10 records have [adduct](https://biothings.ncats.io/dgidb/query?q=association.relation_name:adduct) 
    * currently mapped to affects_activity_of (466 records)
        * 288 records have [modulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:modulator) 
        * 178 records have [allosteric_modulator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:allosteric_modulator) 
    * currently mapped to positively_regulates (311 records)
        * all 311 records have [activator](https://biothings.ncats.io/dgidb/query?q=association.relation_name:activator) 
    * currently mapped to molecularly_interacts_with (266 records)
        * all 266 records have [antibody](https://biothings.ncats.io/dgidb/query?q=association.relation_name:antibody) 
    * currently mapped to increases_degradation_of (62 records)
        * all 62 records have [substrate](https://biothings.ncats.io/dgidb/query?q=association.relation_name:substrate) 
    * currently mapped to derives_from (41 records)
        * all 41 records have [product_of](https://biothings.ncats.io/dgidb/query?q=association.relation_name:product_of) 
    * currently mapped to decreases_expression_of (5 records)
        * all 5 records have [antisense_oligonucleotide](https://biothings.ncats.io/dgidb/query?q=association.relation_name:antisense_oligonucleotide) 
    * currently mapped to affects_degradation_of (5 records)
        * all 5 records have [cleavage](https://biothings.ncats.io/dgidb/query?q=association.relation_name:cleavage)

**Comment by colleenXu** [comment] 2022-01-03 07:30
Should be addressed by https://github.com/NCATS-Tangerine/translator-api-registry/commit/a3aabc0bc6e26c5b6b9814eae61afd977e7363e8

However, the query in the original post still won't return the desired data.

I think this is alright after looking at the [direction of the data](https://dgidb.org/interactions/a0d25cdf-c8b8-49c6-95ef-88572080f885#_summary). It looks like `Bortezomib` -(decreases_activity_of)-> `SEM1`....and that is what I did in the commit above. This triple wouldn't be returned by the query in the original post, since the predicate would be inverted (activity_decreased_by). 

To return this triple, the query would have to be `SEM1` -(activity_decreased_by)-> `SmallMolecule` or `SEM1` <-(decreases_activity_of)- `SmallMolecule`....

**Comment by andrewsu** [comment] 2022-01-04 05:23
@colleenXu so would you agree that the data presented in https://biothings.ncats.io/dgidb/query?q=subject.NCBIGene:7979%20AND%20object.name:BORTEZOMIB (shown below) is actually backward of what is shown in https://dgidb.org/interactions/a0d25cdf-c8b8-49c6-95ef-88572080f885#_summary and https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL325041/, and therefore this seems to indicate a bug in the dgidb parser?

```
{
  "took": 0,
  "total": 2,
  "max_score": 14.561249,
  "hits": [
    {
      "_id": "d86ff0fa9ff42d29",
      "_score": 14.561249,
      "association": {
        "edge_label": "decreases_activity_of",
        "interaction_group_score": "0.47",
        "provided_by": "ChemblInteractions",
        "relation_name": "inhibitor"
      },
      "object": {
        "CHEMBL_COMPOUND": "CHEMBL.COMPOUND:CHEMBL325041",
        "id": "CHEMBL.COMPOUND:CHEMBL325041",
        "name": "BORTEZOMIB"
      },
      "subject": {
        "NCBIGene": "7979",
        "SYMBOL": "SEM1",
        "id": "NCBIGene:7979"
      }
    },
    ...
  ]
}
```

**Comment by colleenXu** [comment] 2022-01-04 06:45
@andrewsu I agree that the biothings API would better match the data (chembl / dgidb links) if the subject was the chemical + the object is the gene. This [link](https://dgidb.org/interaction_types) is also useful for understanding the relations....it looks like the subject is often the drug and the relations can be organized by "their effect" (inhibitory, activating). 

I can edit the current dgidb x-bte annotation with this in mind, let me know....

**Comment by andrewsu** [comment] 2022-01-05 07:04
@colleenXu can you do some spot checking to see if it seems to be universally true that the subject/object should be reversed (or the predicate reversed)?  If so, then yes, I think let's just edit the dgidb x-bte annotation to reflect that, including a prominently-placed comment to note that in an ideal world, the parser should be updated.  (I'd normally also suggest creating an issue to update the parser, but given that the file hasn't been updated since May 2021 (https://dgidb.org/downloads) and the source of the parser isn't clear between https://github.com/ravila4/DGIdb and https://github.com/kevinxin90/dgidb, I think the quick and dirty solution here is warranted...)

**Comment by colleenXu** [comment] 2022-01-05 20:19
@andrewsu there is an issue for updating the API / parser open https://github.com/biothings/pending.api/issues/40

**Comment by colleenXu** [comment] 2022-01-05 23:08
noting current parser issues:
- some chem may have incorrectly imported IDs (have a wikidata ID and a non-matching CHEMBL ID in the object.id field...)
- the relationships in DGIdb are drug -> gene, but the API is set up with subject as gene and object as chem

**Comment by colleenXu** [comment] 2022-01-08 05:38
Fix made here: https://github.com/NCATS-Tangerine/translator-api-registry/commit/159866b7970b37135f1a3f7d4d28d76032c4ca4d

**Comment by colleenXu** [comment] 2022-01-08 05:49
@andrewsu the original query should work as intended now...I realized that it's stated as SEM1  <-(predicates)- SmallMolecule. 

We now get this record back in knowledge_graph.edges
```
                "dd961a001791de5ca1d8d8cb99b7dea7": {
                    "predicate": "biolink:decreases_activity_of",
                    "subject": "PUBCHEM.COMPOUND:387447",
                    "object": "NCBIGene:7979",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-dgidb"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "source",
                            "value": "ChemblInteractions"
                        },
                        {
                            "attribute_type_id": "relation",
                            "value": "inhibitor"
                        },
                        {
                            "attribute_type_id": "dgidb_interaction_group_score",
                            "value": "0.47"
                        }
                    ]
                },
```

**Comment by colleenXu** [comment] 2022-01-08 05:53
Here's the response I'm getting now to the original query (SEM1):
[SEM1.txt](https://github.com/biothings/BioThings_Explorer_TRAPI/files/7832637/SEM1.txt)

![Screen Shot 2022-01-07 at 9 52 46 PM](https://user-images.githubusercontent.com/43731687/148633321-a0598fd3-eac3-49d8-8a05-bf52213d0c0a.png)

**Closed as completed** 2022-01-10 20:24 UTC
