### ISSUE TITLE
"explain" query returning server errors

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#714] opened 2023-08-24 23:30 UTC
This appears to be at least a semi-reproducible error. I ran the query below several times -- some through the Benchmarks tool, some manually via postman -- and I've gotten 2 `502` errors and 3 `500` errors.  (When I get 500 errors, the error description is `TypeError: TypeError: qualifier.replace is not a function`.) All on our prod instance https://bte.transltr.io/v1/query.  Several other three-hop queries in our [DrugMechDB benchmark](https://github.com/TranslatorSRI/Benchmarks/tree/main/config/DrugMechDB) appear to be failing for similar reasons.

I haven't (yet) run it on a local instance to look at the console logs, but just creating this issue to track further debugging... (**EDIT:** I ran it three times on a local instance and it successfully completed each time.)

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "Drug": {
          "ids": [
            "MESH:D005640"
          ]
        },
        "Protein": {
          "categories": [
            "biolink:Protein"
          ]
        },
        "BiologicalProcess": {
          "categories": [
            "biolink:BiologicalProcess"
          ]
        },
        "Disease": {
          "ids": [
            "MESH:D016649"
          ]
        }
      },
      "edges": {
        "e01": {
          "object": "Drug",
          "subject": "Protein",
          "predicates": [
            "biolink:related_to"
          ]
        },
        "e02": {
          "object": "Protein",
          "subject": "BiologicalProcess",
          "predicates": [
            "biolink:related_to"
          ]
        },
        "e03": {
          "object": "BiologicalProcess",
          "subject": "Disease",
          "predicates": [
            "biolink:related_to"
          ]
        }
      }
    }
  }
}
```

**Comment by tokebe** [comment] 2023-08-28 13:17
502 errors are likely problems with ITRB. `TypeError: qualifier.replace is not a function` has [an existing issue](https://github.com/biothings/biothings_explorer/issues/713).

**Comment by tokebe** [comment] 2023-08-28 16:57
Closing as duplicate of #713.

**Closed as completed by tokebe** 2023-08-28 16:57 UTC
Labels: bug
